### ISSUE TITLE
https://railsbump.org is down

### ISSUE THREAD

**Issue by etagwerker** [manuelmeurer/railsbump#28]
Hi @manuelmeurer, 

It seems that there is an issue with the website. 

<img width="925" alt="Screen Shot 2020-05-07 at 8 57 12 AM" src="https://user-images.githubusercontent.com/17584/81297280-089cf700-9041-11ea-8adf-91d2f4e165ad.png">
Any way I can help getting it back online? 

Let me know!

**Comment by alexeyschepin** [comment]
The website is still down.

**Comment by manuelmeurer** [comment]
Fixed! There's still not much to see unfortunately, since I didn't find time to continue working on it...
