### ISSUE TITLE
 Add railsbump to a pipeline.

### ISSUE THREAD

**Issue by bronzdoc** [manuelmeurer/railsbump#51]
@manuelmeurer It would be nice to have a pipeline with different environments also that would allow us to setup `heroku review apps` so a new app is created with every PR to test it.

What you think?

![Screen Shot 2020-05-19 at 10 50 07 PM](https://user-images.githubusercontent.com/4595174/82406213-4592c180-9a23-11ea-82ea-251b47b3a215.png)

**Comment by manuelmeurer** [comment]
Sure, sounds good!
What do you need me to do?
I haven't worked with Heroku pipelines yet...

**Comment by bronzdoc** [comment]
@manuelmeurer I apologize for the late response.

The main reason for this was to configure review-apps so I could debug the deployment issues in https://github.com/manuelmeurer/railsbump/issues/48, since review-apps will deploy every PR and create it's own url. But I saw you fixed it 🙂

**Comment by bronzdoc** [comment]
What in the issue tracker has the highest priority for you to be added/fixed?

I'll dedicate some time this week and weekend to Railsbump and I would love to know what are the priorities

**Comment by manuelmeurer** [comment]
I'd say #45, #42, and #30 are the issues that we should tackle next. Grab whichever you like most. :)
